version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - dependencies🫂
    assignees:
      - "mkkelvinhk"
    reviewers:
      - "mkkelvinhk"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - dependencies🫂
    assignees:
      - "mkkelvinhk"
    reviewers:
      - "mkkelvinhk"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - dependencies🫂
    assignees:
      - "mkkelvinhk"
    reviewers:
      - "mkkelvinhk"
